config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations:      'registrations',
                                    sessions:           'sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    put 'address_settings', to: 'registrations#address_settings'
  end

  root 'home_page#index'

  resources :categories, only: [:show], path: 'catalog'
  resources :books, only: [:show]
  resources :reviews, only: [:create]
  resources :order_items, only: [:create, :update, :destroy]
  resources :checkouts
  resource  :cart, only: [:show, :update]
  resources :orders, only: [:show, :index]
  resources :orders do
    get 'continue_shopping', on: :member
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  include GettingAddress

  before_save { update_total_price }

  has_many :order_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true
  belongs_to :credit_card, optional: true

  SORT_TITLES = {all: 'All', in_progress: 'In Progress', in_queue: 'Waiting for processing',
                 in_delivery: 'In Delivery', delivered: 'Delivered', canceled: 'Canceled'}.freeze

  default_scope { order(created_at: :desc) }
  scope :in_progress, -> { where(state: :in_progress) }
  scope :in_queue, -> { where(state: :in_queue) }
  scope :in_delivery, -> { where(state: :in_delivery) }
  scope :delivered, -> { where(state: :delivered) }

  aasm column: 'state', whiny_transitions: false do
    state :in_progress, initial: true
    state :in_queue, :in_delivery, :delivered, :canceled

    event :confirm do
      after do
        CheckoutMailer.complete_email(user.id, self.id).deliver_now
      end
      transitions from: :in_progress, to: :in_queue
    end

    event :start_delivery do
      transitions from: :in_queue, to: :in_delivery
    end

    event :finish_delivery do
      transitions from: :in_delivery, to: :delivered
    end

    event :cancel do
      transitions from: [:in_queue, :in_delivery, :in_progress], to: :canceled
    end
  end

  def subtotal
    order_items.collect(&:total_price).sum
  end

  private

  def use_coupon
    return 0 if coupon >= subtotal
    coupon
  end

  def update_total_price
    self.total_price = subtotal - use_coupon + (delivery.nil? ? 0 : delivery.price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    # @orders = SortOrdersService.new(params[:sort_type], current_user.orders).sort_orders
    @orders = current_user.orders.send(choose_sort)
  end

  def show
  end

  def continue_shopping
    session[:order_id] = params[:id]
    redirect_to category_path(1)
  end

  private

  def choose_sort
    params[:sort_type] || :all
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

  def order_state_title(sort_type = :all)
    choose_sort = params[:sort_type] ? params[:sort_type] : sort_type
    Order::SORT_TITLES[choose_sort.to_sym]
  end
end

app/views/orders/_mobile_orders.html.haml
- @orders.each do |order|
  .general-cart-item.divider-lg-bottom.pt-0
    %table.table
      %tr
        %td.col-half
          %span.in-grey-600= t('number')
        %td.col-half
          %span.general-order-number= link_to track_number(order), order_path(order), class: 'in-gold-500'
      %tr
        %td
          %span.in-grey-600= t('number')
        %td
          %span.in-grey-900.font-16.font-weight-light= order.created_at.strftime("%Y-%m-%d")
      %tr
        %td
          %span.in-grey-600= t('status')
        %td
          %span.font-16.in-grey-900.font-weight-light= order_state_title(order.state)
      %tr
        %td
          %span.in-grey-600= t('total')
        %td
          %strong.font-16= shifting_price_to_currency(order.total_price)

app/views/orders/_orders.html.haml
- @orders.each do |order|
  %tr
    %td
      %span.general-order-number= link_to track_number(order), order_path(order), class: 'in-gold-500'
    %td
      %span.in-grey-900.font-16.font-weight-light= order.created_at.strftime("%Y-%m-%d")
    %td
      %span.font-16.in-grey-900.font-weight-light= order_state_title(order.state)
    %td
      %strong.font-16= shifting_price_to_currency(order.total_price)

app/views/orders/_sort_dropdown.html.haml
%p.in-grey-600.small.mb-10.visible-xs= t('sort_by')
.dropdown.general-order-dropdown.mb-20
  %a.dropdown-toggle.dropdown-btn.width-100{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
    = order_state_title
    %i.fa.fa-angle-down.dropdown-icon
  %ul.dropdown-menu
    %li
      = link_to "All", orders_path(sort_type: :all)
    %li
      = link_to "Waiting for processing", orders_path(sort_type: :in_queue)
    %li
      = link_to "In Progress", orders_path(sort_type: :in_progress)
    %li
      = link_to "In Delivery", orders_path(sort_type: :in_delivery)
    %li
      = link_to "Delivered", orders_path(sort_type: :delivered)

app/views/orders/index.html.haml
%main.container.general-main-wrap
  - if current_user.orders.any?
    %h1.mt-0.mb-25= t('my_orders')
    = render "sort_dropdown"
    .visible-xs
      = render "mobile_orders"
    .hidden-xs.mb-res-50
      %table.table.table-hover
        %thead
          %tr
            %th
              %span.in-grey-600= t('number')
            %th
              %span.in-grey-600= t('completed_at')
            %th
              %span.in-grey-600= t('status')
            %th
              %span.in-grey-600= t('total')
        %tbody
          = render "orders"
  - else
    %h1.text-center= t('dont_have_orders')
    %h1.text-center= link_to t('go_shop'), category_path(1), class: 'in-gold-500'

app/views/orders/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= "Order " + track_number(@order)
  .row.mb-20
    = (render partial: "checkouts/address_info", locals: {type: "shipping", edit: false}) if @order.get_address("shipping")
    = (render partial: "checkouts/address_info", locals: {type: "billing", edit: false}) if @order.get_address("billing")
    - unless @order.delivery.nil?
      .col-sm-3
        %h3.general-subtitle.mt-0= t('shipments')
        %p.general-address
          = @order.delivery.name
    - unless @order.credit_card.nil?
      .col-sm-3
        %h3.general-subtitle.mt-0= t('payment_info')
        %p.general-address
          = "**** **** **** #{@order.credit_card.card_number[-4..-1]}"
          %br
          = @order.credit_card.try(:mm_yy)
  .visible-xs
    = render "checkouts/mobile_items"
  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600= t('product')
          %th.col-method
          %th
            %span.in-grey-600= t('price')
          %th
            %span.in-grey-600= t('quantity')
          %th
            %span.in-grey-600= t('total')
      %tbody
        = render "checkouts/items"
  .text-center.general-text-right
    %p.in-gold-500.font-18= t('summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render "checkouts/summary"
    .text-center
      = (link_to t('continue_shopping'), continue_shopping_order_path(@order.id), class: "btn btn-default mb-20") if @order.state == "in_progress"