config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations:      'registrations',
                                    sessions:           'sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    put 'address_settings', to: 'registrations#address_settings'
  end

  root 'home_page#index'

  resources :categories, only: [:show], path: 'catalog'
  resources :books, only: [:show]
  resources :reviews, only: [:create]
  resources :order_items, only: [:create, :update, :destroy]
  resources :checkouts
  resource  :cart, only: [:show, :update]
  resources :orders, only: [:show, :index]
  resources :orders do
    get 'continue_shopping', on: :member
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_order
    @order_items = @order.order_items
  end

  def update
    @coupon = Coupon.find_by(code: params[:coupon_code])
    @order = current_order
    if @coupon
      @order.update_attributes(coupon: @coupon.discount)
      redirect_to cart_path, notice: I18n.t('flash.coupon_activate')
    else
      redirect_to cart_path, alert: I18n.t('flash.wrong_coupon')
    end
  end
end

app/views/carts/_items.html.haml
.hidden-xs
  %table.table.table-hover
    %tr.no-hover
      %th.col-pic.pl-0
        %span.in-grey-600= t('product')
      %th.col-title
      %th.col-price
        %span.in-grey-600= t('price')
      %th.col-quantity
        %span.in-grey-600= t('quantity')
      %th.col-total
        %span.in-grey-600= t('subtotal')
      %th.col-close
    - @order_items.each do |item|
      %tr
        %td
          .general-img-wrap-table
            = image_tag item.book.picture.thumb, class: 'cart-img-shadow pull-left width-full', alt: "design-book"
        %td
          %p.general-title
            = link_to "#{item.book.title}", item.book
        %td
          %span.font-16.in-gold-500= shifting_price_to_currency(item.book.price)
        %td
          .input-group
            = link_to order_item_path(item, quantity: "#{item.quantity - 1}", operation: :minus), method: :patch, class: "#{'not-active' if item.quantity <= 1} input-link" do
              %i.fa.fa-minus.line-height-40
            %input.form-control.quantity-input{type: "text", value: "#{item.quantity}", disabled: true}
            = link_to order_item_path(item, quantity: "#{item.quantity + 1}"), method: :patch, class: "input-link" do
              %i.fa.fa-plus.line-height-40
        %td
          %span.font-16.in-gold-500= shifting_price_to_currency(item.total_price)
        %td
          = link_to item, method: :delete, data: {confirm: t('sure?')}, class: "close general-cart-close", 'aria-label': 'Close' do
            %span{'aria-hidden': "true"} &times;

app/views/carts/_mobile_items.html.haml
.visible-xs
  - @order_items.each do |item|
    .general-cart-item.divider-lg-bottom
      = link_to item, method: :delete, data: {confirm: t('sure?')}, class: "close general-cart-close", 'aria-label': 'Close' do
        %span{'aria-hidden': "true"} &times;
      .general-img-wrap-table
        %img.cart-img-shadow.width-full= image_tag item.book.picture.thumb, class: 'cart-img-shadow pull-left width-full', alt: "design-book"
      %p.general-title= link_to "#{item.book.title}", item.book
      %table.table
        %tr
          %td
            %span.in-grey-600= t('price')
          %td
            %span.font-16.in-gold-500= shifting_price_to_currency(item.book.price)
        %tr
          %td.vertical-middle
            %span.in-grey-600= t('quantity')
          %td
            .input-group
              = link_to order_item_path(item, quantity: "#{item.quantity - 1}", operation: :minus), method: :patch, class: "#{'not-active' if item.quantity <= 1} input-link" do
                %i.fa.fa-minus.line-height-40
              %input.form-control.quantity-input{type: "text", value: "#{item.quantity}", disabled: true}
              = link_to order_item_path(item, quantity: "#{item.quantity + 1}"), method: :patch, class: "input-link" do
                %i.fa.fa-plus.line-height-40
        %tr
          %td
            %span.in-grey-600= t('subtotal')
          %td
            %span.font-16.in-gold-500= shifting_price_to_currency(item.total_price)

app/views/carts/show.html.haml
%main.container.general-main-wrap
  - if @order_items.any?
    %h1.general-title-margin= t('cart')
    = render "mobile_items"
    = render "items"
    .general-order-wrap
      .row
        .col-sm-4
          = form_tag cart_path, method: :put do
            .input-group.general-input-group
              %label.font-weight-light= t('coupon_code')
              = text_field_tag "coupon_code", "", placeholder: t('coupon_code'), class: "form-control mb-30"
              %div
                = submit_tag t('update_cart'), class: "btn btn-primary mb-15 res-block"
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18= t('summary')
            %table.general-summary-table.general-summary-table-right.general-text-right
              %tr
                %td
                  %p.font-16= t('subtotal') + ":"
                %td
                  %p.font-16= shifting_price_to_currency(@order.subtotal)
              %tr
                %td
                  %p.font-16= t('coupon') + ":"
                %td
                  %p.font-16= shifting_price_to_currency(@order.coupon)
              %tr
                %td
                  %strong.font-18= t('total') + ":"
                %td
                  %strong.font-18= shifting_price_to_currency(@order.total_price)
            = button_to t('checkout'), checkouts_path, method: :get, class: "btn btn-default mb-20 visible-xs-inline-block"
    = button_to t('checkout'), checkouts_path, method: :get, class: "btn btn-default mb-20 hidden-xs center-block"
  - else
    %h1.text-center= t('empty_cart')
    %h1.text-center= link_to t('go_shop'), category_path(1), class: 'in-gold-500'