config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations:      'registrations',
                                    sessions:           'sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_scope :user do
    put 'address_settings', to: 'registrations#address_settings'
  end

  root 'home_page#index'

  resources :categories, only: [:show], path: 'catalog'
  resources :books, only: [:show]
  resources :reviews, only: [:create]
  resources :order_items, only: [:create, :update, :destroy]
  resources :checkouts
  resource  :cart, only: [:show, :update]
  resources :orders, only: [:show, :index]
  resources :orders do
    get 'continue_shopping', on: :member
  end
end

app/views/layouts/_footer.html.haml
%footer.navbar.navbar-inverse.footer.mb-0
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to t('home'), root_path, class: "nav-link"
          %li
            = link_to t('shop'), category_path(1), class: "nav-link"
          - if user_signed_in?
            %li
              = link_to t('orders'), orders_path, class: "nav-link"
            %li
              = link_to t('settings'), edit_user_registration_path, class: "nav-link"
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Botanic Center', root_path, class: 'navbar-brand'
      = link_to cart_path, class: "shop-link pull-right visible-xs" do
        %span.shop-icon
          %span.shop-quantity= items_in_cart
    = link_to cart_path, class: "shop-link pull-right hidden-xs" do
      %span.shop-icon
        %span.shop-quantity= items_in_cart
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      = render "layouts/mobile_navbar"
      = render "layouts/navbar"

app/views/layouts/_mobile_navbar.html.haml
.visible-xs
  %button.close{type: "button", 'aria-label': "Close"}
    %span{'aria-hidden': "true"} &times;
  %ul.nav.navbar-nav
    %li
      = link_to t('home'), {}, type: "button", 'data-toggle': "collapse", href: "#menu", 'aria-expanded': "false", 'aria-controls': "menu"
      %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
        - categories_list.find_each do |category|
          %li
            = link_to root_path(category_id: category.id), class: "collapse-link" do
              = category.title
    %li
      = link_to t('shop'), category_path(1)
    - if user_signed_in?
      %li
        %a{type: "button", 'data-toggle': "collapse", href: "#account", 'aria-expanded': "false", 'aria-controls': "menu"} My account
        %ul#account.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
          %li
            = link_to t('orders'), orders_path, class: "collapse-link"
          %li
            = link_to t('settings'), edit_user_registration_path, class: "collapse-link"
          - if can? :access, :rails_admin
            %li
              = link_to t('admin_panel'), rails_admin.dashboard_path, class: "collapse-link"
          %li
            = link_to t('logout'), destroy_user_session_path, method: :delete, class: "collapse-link"
    - else
      %li
        = link_to t('login'), new_user_session_path
      %li
        = link_to t('signup'), new_user_registration_path

app/views/layouts/_navbar.html.haml
.hidden-xs
  %ul.nav.navbar-nav
    %li.dropdown
      = link_to t('home'), {}, class: "dropdown-toggle", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"
      %ul.dropdown-menu
        - categories_list.find_each do |category|
          %li
            = link_to root_path(category_id: category.id) do
              = category.title
      %li
        = link_to t('shop'), category_path(1)
    - if user_signed_in?
      %li.dropdown
        = link_to t('account'), {}, class: "dropdown-toggle", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"
        %ul.dropdown-menu
          %li
            = link_to t('orders'), orders_path
          %li
            = link_to t('settings'), edit_user_registration_path
          - if can? :access, :rails_admin
            %li
              = link_to t('admin_panel'), rails_admin.dashboard_path
          %li.divider{role: "separator"}
          %li
            = link_to t('logout'), destroy_user_session_path, method: :delete
    - else
      %li
        = link_to t('login'), new_user_session_path
      %li
        = link_to t('signup'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bookstore
    %meta{name: "viewport", content: "width=device-width"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{id: "#{controller_name}-#{action_name}"}
    = render 'layouts/header'
    - flash.each do |message_type, message|
      %div{class: "alert alert-#{change_class(message_type)}"}
        %button{type: "button", class: "close", "data-dismiss": "alert", "aria-label": "Close"}
          %span{"aria-hidden": "true"} &times;
        = message
    = yield
    = render "layouts/footer"
    %script{src: "https://use.fontawesome.com/67602d7308.js"}